import { MusicContextProvider } from "./context/MusicContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MusicContextProvider>{children}</MusicContextProvider>
      </body>
    </html>
  );
}
