import { MusicContextProvider } from "./context/MusicContext";
import { QueryContextProvider } from "./context/QueryContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <QueryContextProvider>
          <MusicContextProvider>{children}</MusicContextProvider>
        </QueryContextProvider>
      </body>
    </html>
  );
}
